### ISSUE TITLE
Rework signs & songs option

### ISSUE THREAD

**Issue by Xyl-AU** [rockrider69/service.LanguagePreferenceManager#7]
Currently there is an option to ignore signs and songs subtitles when choosing the sub track. I think it would be good to rework this so that signs and songs can be prioritised as well, for dub watchers. Perhaps making signs and songs ignored by default, but adding a custom options suffix like "-ss" to use the signs subs could achieve this. So, for example, if I wanted to watch in English by default but fall back to full subs when there is no dub, I could put the following in custom options.

eng:eng-ss>eng:non>any:eng

**Comment by rockrider69** [comment]
@Xyl-AU 
Thanks for the interest and suggestion, I'll have to think about that !
 
Just to be sure: Eng/Signs&Songs tracks we'd target here contain strictly that (signs and songs translations) and no dialog at all, full, nor forced ?

I am asking because I have seen full subs, or sometimes forced ones, which are including Signs&Songs also. But this might be wrong practices...

Also please note that with this rule (eng:eng-ss>**eng:non**>any:eng) we would indeed prioritize Signs&Songs, over english Forced dialog if ever they both exists separately. No way to get them both in that situation unless a merged Signs/Songs/Forced ;)

**Comment by rockrider69** [comment]
@Xyl-AU
I have been thinking addressing your proposal, a -ss tag to prioritize Signs&Songs subs, and would like to check a couple of things with you :
- I will rather keep the general "Toggle Ignore Signs and Songs" as it is (default false) as well as the alternative possibility to exclude these tracks via the generic "Blacklist keywords list".
- the -ss tag would only be useable in the "custom sub preferences" (exactly as in your example). No new dedicated field/tag in the "normal" sub preferences.
- if present the -ss tag will be tested BEFORE the Toggle Ignore Signs and Songs", or the "Blacklist Keywords" filters, hence take precedence above these. This allows to only overide the current and general ignore rule for specific languages while continue to ignore S&S for all others.

Not sure yet  if I miss something key for the logic, but what do you think of the principles ?

**Comment by rockrider69** [comment]
@Xyl-AU
If you have time please try 1.0.3BETA1 release (just published) and tell me ...

**Comment by rockrider69** [comment]
Hi !
1.0.3 is now final and will soon be pushed to Kodi Repository. Closing this issue.
